### ISSUE TITLE
Where's the docs of what types of comments are supported?

### ISSUE THREAD

**Issue by trusktr** [tj/dox#141]
For example, is it jsdoc syntax? Can I use `@class`?

**Comment by ChiperSoft** [comment]
Dox will import any @ tags that it finds, so you will get at minimum a string representation of the tag's contents.  Some tags it recognizes as special meaning and parses out extra data, but there's no docs on which tags those are.

If you read the source it's pretty easy to spot the list of recognized tags. I'm on my phone so I can't point you at a specific line, I'm afraid. The lib isn't all that large.

**Comment by trusktr** [comment]
Thanks! Yep, I found it.
