### ISSUE TITLE
Idea: Let tags take precedence over what's detected in the code context.

### ISSUE THREAD

**Issue by trusktr** [tj/dox#144]
For example, I have this:

```js
  /*
   * A base application.
   * @class App
   * @extends {Marionette.Application}
   */
  var App = Marionette.Application.extend({
    /* ... */
  });
```

In Backbone/Marionette, that's a `class` definition, but the ctx.type gets set to `declaration` based on the syntax.

I would say let's let comment tags take precedence over code syntax, so that in in cases like these, the ctx.type would be `class` instead of `declaration`, as expected.

**Comment by ChiperSoft** [comment]
I agree, the tags should always trump what dox parses out of the code, but I think that decision should be done by whatever is reading the dox output, not dox itself.  Having the ctx remain as a declaration provides extra context, and is trivial to override by looking at the tags.

**Comment by ChiperSoft** [comment]
IMO (and this may not match @tj or @evindor's view), Dox is only intended to be a parser, not an interpreter.  Interpretation is left for the code that invokes it.

**Comment by trusktr** [comment]
Yeah, that makes sense. I'm using dox-foundation which is depending on dox for the json, so yeah, dox-foundation could make that call. Basically, all the info is there, dox-foundation is preferring the code ctx over the tags.
