### ISSUE TITLE
Idea: show the whole code for a class, etc.

### ISSUE THREAD

**Issue by trusktr** [tj/dox#146]
For example, instead of just having

```js
export class Molecule extends RenderNode {
```

it might be nice to have

```js
export class Molecule extends RenderNode {
  constructor() {
    /* code... */
  }
}
```

Maybe `code` can be renamed to `ctxCode`, and add a `scopeCode` property with the full code, or something along those lines.

**Comment by ChiperSoft** [comment]
Unfortunately, with the way that dox parses everything linearly through the file, this isn't really possible.  Dox has no concept of code blocks as defined by braces, just what code exists between each comment.

**Comment by trusktr** [comment]
True. It'd need a whole lot of re-work. Perhaps code between comments can be appended to a temporary variable starting when a `parentContext` becomes available, then when the `parentContext` ceases to exist the variable gets saved to the parentContext's comment object.
