### ISSUE TITLE
Idea: GitHub flavored markdown.

### ISSUE THREAD

**Issue by trusktr** [tj/dox#147]
Or perhaps just change some config option for the current markdown parser? It seems that every new line gets a `<br>` tag when dox has parsed it with markdown, but on GitHub people are accustomed to single new lines being part of the same paragraph (no `<br>` tag is inserted), and new paragraphs are only made when there are two consecutive new lines.

**Comment by trusktr** [comment]
For example, with dox, if you do something like the following in your jsdoc comment

```
This
is
a
sentence.

This
is
another
sentence.
```

then the dox result looks like

```
This
is
a
sentence.

This
is
another
sentence.
```

due to the `<br>` tags, but the github result will look like

```
This is a sentence.

This is another sentence.
```

Both results have two paragraphs, but dox just inserts the extra `<br>` tags.

**Comment by ChiperSoft** [comment]
See issue #157
