### ISSUE TITLE
[BUG?] /*! ignored */ is not being "ignored", just completely ignored.

### ISSUE THREAD

**Issue by trusktr** [tj/dox#154]
I'm trying something like

```
/*!
 * Ignored.
 */
someCode();
```

but it's not being ignored.

**Comment by trusktr** [comment]
Seems like the comment is *completely* ignored, and when the parser gets to the closing `/` it should set comment.ignore, but it never even makes a comment in my case.

**Comment by trusktr** [comment]
I'm on master branch of dox. This is the actual file in question that it's happening on: https://github.com/trusktr/readem/blob/master/bin/read'em.js

If I put a `console.log(ignore)` right after [this line](https://github.com/trusktr/dox/blob/es6-and-code-style/lib/dox.js#L104) in `lib/dox.js`, it'll get called 5 times instead of the expected 6 times (the 6th comment is the "ignored" comment).

**Comment by ChiperSoft** [comment]
@trusktr please check this issue again as well, I'm not able to reproduce the problem on master, using the file you linked.

```
{
    "tags": [],
    "description": {
      "full": "<p>ignore</p>",
      "summary": "<p>ignore</p>",
      "body": ""
    },
    "isPrivate": false,
    "isConstructor": false,
    "isClass": false,
    "isEvent": false,
    "ignore": true,
    "line": 237,
    "codeStart": 240,
    "code": "console.log(' --- Generating docs...')\ngetVersion(function(version) {\n    setUpCli(version)\n\n    getDox(app.source, {\n        skipSingleStar: !app.singleStar\n    }, function(dox) {\n        if (dox)\n            genDocs(dox, {\n                dox: dox,\n                template: app.template,\n                dest: app.output,\n                source: app.source\n            }, function() {\n                console.log(' --- Done.')\n                serve(app.output, app.port)\n            })\n    })\n})"
  }
```

Re-open if it's still happening for you.
