### ISSUE TITLE
Line breaks are output as `<br/>`

### ISSUE THREAD

**Issue by tomekwi** [tj/dox#157]
```
$ cat <<———— | dox
/**
 * Short summary
 * 
 * Full description
 * whoa, lots of it!
 */
————
...
    "description": {
      "full": "<p>Short summary</p><p>Full description<br />whoa, lots of it!</p>",
      "summary": "<p>Short summary</p>",
      "body": "<p>Full description<br />whoa, lots of it!</p>"
    },
 ...
```

Note the `<br/>`s here and there.

[The very most original markdown spec](http://daringfireball.net/projects/markdown/syntax#p) makes it quite explicit that it shouldn't be so:
> The implication of the “one or more consecutive lines of text” rule is that Markdown supports “hard-wrapped” text paragraphs. This differs significantly from most other text-to-HTML formatters (including Movable Type’s “Convert Line Breaks” option) which translate every line break character in a paragraph into a <br /> tag.

**Comment by ChiperSoft** [comment]
You're issue here would be with the [marked](https://www.npmjs.com/package/marked) package that dox uses, not dox itself.  You can always pass dox the `raw:true` option and do the markdown parsing using a different engine.

**Comment by ChiperSoft** [comment]
The behavior you're seeing _might_ be related to marked's `breaks` option, which you can override by calling dox.setMarkedOptions() with your own settings.

**Comment by tomekwi** [comment]
Thanks for the explanation.

Since that's markdown's default behaviour, wouldn't it be reasonable to set it as the default in dox?

**Comment by ChiperSoft** [comment]
Probably, yes. However since that could have significant impact on the output, it's the kind of change that should really be reserved for a major release.

I'm also considering switching dox over to using commonmark instead of marked, which would also necessitate a major release. I'll be opening a discussion issue to get people's feedback on that change.

**Comment by tomekwi** [comment]
> I'm also considering switching dox over to using commonmark

:+1: I'm looking forward to that :)
