### ISSUE TITLE
fileOverview/file/overview

### ISSUE THREAD

**Issue by scottnath** [tj/dox#169]
Hi dox team,

Looks like the [@file](http://usejsdoc.org/tags-file.html) tag is not explicitly supported. This means extras like @requires and @author don't get grabbed other than putting that data into the string/html nodes like so:
```
    "tags": [
      {
        "type": "file",
        "string": "Uses Gulpjs and gulp-inject to glob files  @author       Scott Nath",
        "html": "<p>Uses Gulpjs and gulp-inject to glob files  @author       Scott Nath</p>"
      }
    ],
```

Am I correct in this assumption?
How difficult would it be to add in functionality for this tag?

thanks,
Scott

**Comment by ChiperSoft** [comment]
Curious, it shouldn't need to be explicitly supported for the author tag to be detected. This sounds like a parsing bug. Could you provide a gist with the code that produced that output?

**Comment by scottnath** [comment]
here it is:
https://gist.github.com/scottnath/bcf5f1ec55fcc8e1017f

**Comment by ChiperSoft** [comment]
No, I mean the code that you ran dox against that produced that output.  I wrote my own test using the example on that JSDoc page and Dox is parsing both the file and author tags correctly, so I need to see what is different about your case.

**Comment by scottnath** [comment]
At the top of the gist, I pointed to this file:
https://github.com/pattern-library/pattern-library-utilities/blob/master/lib/get-options.js

Is that what you mean by the code I ran dox against?

**Comment by ChiperSoft** [comment]
ah, yes, thank you.  will see what I can find.

**Comment by ChiperSoft** [comment]
I'm able to reproduce it with your sample. It doesn't appear to matter what the tags are, so its definitely something wrong with tag parsing in general.

**Comment by scottnath** [comment]
I see. Can I do anything else to help with this bug?

**Comment by ChiperSoft** [comment]
Wow.  Well, I fixed the bug, but that broke a LOT of tests that for some dumb reason were coded to account for that very bug, so it's gonna take me a bit to update all these tests. Might have a fix by end of day, might not.

**Comment by scottnath** [comment]
wow @ChiperSoft thanks so much for being on this!

**Comment by ChiperSoft** [comment]
Disregard previous comment, I was misread my test output. Problem is now fixed, will push out a new release today.

**Comment by ChiperSoft** [comment]
0.8.0 is now published

**Comment by scottnath** [comment]
Thank you for taking care of this.
