### ISSUE TITLE
Add support for ES2016 template literals

### ISSUE THREAD

**Issue by alex3683** [tj/dox#184]
The title says it all. Would be nice to have support for [template literals](http://exploringjs.com/es6/ch_template-literals.html). :)
Without support for these, a single tick or double quote within a template literal would lead to unexpected parsing behavior.

Example: `` `It's all good` ``

Here, dox will detect the start of a string at the single tick and parse all subsequent code as part of that string. `` `It is all good` `` will work by chance because no string or comment is detected and the parser just skips it.

**Comment by ChiperSoft** [comment]
Yeah, that should be easy to fix. Just add the back tic to the list of string detections and create a test case for it.

**Comment by ChiperSoft** [comment]
Fixed in 0.9.0
