### ISSUE TITLE
NEEDS example of "opinionated formatting template"...

### ISSUE THREAD

**Issue by ddopson** [tj/dox#38]
See the discussion on this StackOverflow posting:
http://stackoverflow.com/questions/6096649/documenting-node-js-projects/6995688#6995688

Basically, mere mortals are intimidated by the task of creating a template to turn pure "unopinionated" JSON code structure metadata into human consumable "opinionated" HTML.  The concept of factoring apart the parser from the formatter is great; we just need an example of how a template would work.... a starting point.  Adding this (plus a mention in the README.md) would go a long way towards making this module consumable by others.  

As much as I'd love to do the work myself and submit a "pull request", honestly, I'm not entirely sure how to create such a template either.  Not that I'd ever admit that... ;)

Cheers,
  ---  Dave

**Comment by q2dg** [comment]
Why is this issue closed??!!

**Comment by ChiperSoft** [comment]
It's a three and a half year old issue that I feel has been answered by the participants.  There are many examples here of how to format dox output in various template languages.

If someone wants to make a PR to enhance the documentation with concrete examples, I'll merge it, but I don't agree that in 2015 people NEED to see an example template.
