### ISSUE TITLE
add support for `let`, `const` and other other ES6 / harmony / js 1.7 constructs

### ISSUE THREAD

**Issue by gregglind** [tj/dox#79]
Patches that get 'most of the way there' incoming.

**Comment by gregglind** [comment]
Sorry I let this go for a while. I am not sure of the right solution here.  One is to transpile first.  Esprima and friends support es6 now, so maybe should be less of an issue, if you're actually parsing the tree.

**Comment by shellscape** [comment]
Unfortunately Esprima moves at a snail's pace. they barely have support for ES6, unless their docs are out of date. http://esprima.org/doc/es6.html

**Comment by ChiperSoft** [comment]
Closed via 797580e6
